dbt_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DEV_DBT_HOST') }}"
      user: "{{ env_var('DEV_DBT_USER') }}"
      password: "{{ env_var('DEV_DBT_PASS') }}"
      port: 5432
      dbname: dbt_demo
      schema: public
  
    stage:
      type: postgres
      host: "{{ env_var('STAGE_DBT_HOST') }}"
      user: "{{ env_var('STAGE_DBT_USER') }}"
      password: "{{ env_var('STAGE_DBT_PASS') }}"
      port: 5432
      dbname: dbt_demo
      schema: public