dbt_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'dbt_user') }}"
      password: "{{ env_var('DBT_PASS', 'dbt_pass') }}"
      port: 5432
      dbname: dbt_demo
      schema: public
  
    stage:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'dbt_user') }}"
      password: "{{ env_var('DBT_PASS', 'dbt_pass') }}"
      port: 5432
      dbname: dbt_demo
      schema: public